# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 1024)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 1024))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 1024))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1980, 1080))
        self.label.setMinimumSize(QtCore.QSize(1980, 1080))
        self.label.setMaximumSize(QtCore.QSize(1980, 1080))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.title_hanoi_tower = QtWidgets.QLabel(self.centralwidget)
        self.title_hanoi_tower.setGeometry(QtCore.QRect(310, 0, 731, 61))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(42)
        self.title_hanoi_tower.setFont(font)
        self.title_hanoi_tower.setAlignment(QtCore.Qt.AlignCenter)
        self.title_hanoi_tower.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.title_hanoi_tower.setObjectName("title_hanoi_tower")
        self.game = QtWidgets.QFrame(self.centralwidget)
        self.game.setGeometry(QtCore.QRect(-490, 60, 1851, 901))
        self.game.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.game.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.game.setFrameShadow(QtWidgets.QFrame.Raised)
        self.game.setObjectName("game")
        self.shpil8 = QtWidgets.QLabel(self.game)
        self.shpil8.setGeometry(QtCore.QRect(590, 110, 1, 501))
        self.shpil8.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.shpil8.setText("")
        self.shpil8.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.shpil8.setObjectName("shpil8")
        self.shpil7 = QtWidgets.QLabel(self.game)
        self.shpil7.setGeometry(QtCore.QRect(720, 110, 1, 501))
        self.shpil7.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.shpil7.setText("")
        self.shpil7.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.shpil7.setObjectName("shpil7")
        self.shpil6 = QtWidgets.QLabel(self.game)
        self.shpil6.setGeometry(QtCore.QRect(890, 110, 1, 501))
        self.shpil6.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.shpil6.setText("")
        self.shpil6.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.shpil6.setObjectName("shpil6")
        self.shpil5 = QtWidgets.QLabel(self.game)
        self.shpil5.setGeometry(QtCore.QRect(1040, 110, 1, 501))
        self.shpil5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.shpil5.setText("")
        self.shpil5.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.shpil5.setObjectName("shpil5")
        self.shpil4 = QtWidgets.QLabel(self.game)
        self.shpil4.setGeometry(QtCore.QRect(1210, 110, 1, 501))
        self.shpil4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.shpil4.setText("")
        self.shpil4.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.shpil4.setObjectName("shpil4")
        self.shpil3 = QtWidgets.QLabel(self.game)
        self.shpil3.setGeometry(QtCore.QRect(1400, 110, 1, 501))
        self.shpil3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.shpil3.setText("")
        self.shpil3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.shpil3.setObjectName("shpil3")
        self.shpil2 = QtWidgets.QLabel(self.game)
        self.shpil2.setGeometry(QtCore.QRect(1580, 110, 1, 501))
        self.shpil2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.shpil2.setText("")
        self.shpil2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.shpil2.setObjectName("shpil2")
        self.shpil1 = QtWidgets.QLabel(self.game)
        self.shpil1.setGeometry(QtCore.QRect(1700, 110, 1, 501))
        self.shpil1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.shpil1.setText("")
        self.shpil1.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.shpil1.setObjectName("shpil1")
        self.blin = QtWidgets.QLabel(self.game)
        self.blin.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin.setText("")
        self.blin.setObjectName("blin")
        self.blin_2 = QtWidgets.QLabel(self.game)
        self.blin_2.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_2.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_2.setText("")
        self.blin_2.setObjectName("blin_2")
        self.blin_3 = QtWidgets.QLabel(self.game)
        self.blin_3.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_3.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_3.setText("")
        self.blin_3.setObjectName("blin_3")
        self.blin_4 = QtWidgets.QLabel(self.game)
        self.blin_4.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_4.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_4.setText("")
        self.blin_4.setObjectName("blin_4")
        self.blin_5 = QtWidgets.QLabel(self.game)
        self.blin_5.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_5.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_5.setText("")
        self.blin_5.setObjectName("blin_5")
        self.blin_6 = QtWidgets.QLabel(self.game)
        self.blin_6.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_6.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_6.setText("")
        self.blin_6.setObjectName("blin_6")
        self.blin_7 = QtWidgets.QLabel(self.game)
        self.blin_7.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_7.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_7.setText("")
        self.blin_7.setObjectName("blin_7")
        self.blin_8 = QtWidgets.QLabel(self.game)
        self.blin_8.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_8.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_8.setText("")
        self.blin_8.setObjectName("blin_8")
        self.blin_9 = QtWidgets.QLabel(self.game)
        self.blin_9.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_9.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_9.setText("")
        self.blin_9.setObjectName("blin_9")
        self.blin_10 = QtWidgets.QLabel(self.game)
        self.blin_10.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_10.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_10.setText("")
        self.blin_10.setObjectName("blin_10")
        self.blin_11 = QtWidgets.QLabel(self.game)
        self.blin_11.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_11.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_11.setText("")
        self.blin_11.setObjectName("blin_11")
        self.blin_12 = QtWidgets.QLabel(self.game)
        self.blin_12.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_12.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_12.setText("")
        self.blin_12.setObjectName("blin_12")
        self.blin_13 = QtWidgets.QLabel(self.game)
        self.blin_13.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_13.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_13.setText("")
        self.blin_13.setObjectName("blin_13")
        self.blin_14 = QtWidgets.QLabel(self.game)
        self.blin_14.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_14.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_14.setText("")
        self.blin_14.setObjectName("blin_14")
        self.blin_15 = QtWidgets.QLabel(self.game)
        self.blin_15.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_15.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_15.setText("")
        self.blin_15.setObjectName("blin_15")
        self.blin_16 = QtWidgets.QLabel(self.game)
        self.blin_16.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_16.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_16.setText("")
        self.blin_16.setObjectName("blin_16")
        self.blin_17 = QtWidgets.QLabel(self.game)
        self.blin_17.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_17.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_17.setText("")
        self.blin_17.setObjectName("blin_17")
        self.blin_18 = QtWidgets.QLabel(self.game)
        self.blin_18.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_18.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_18.setText("")
        self.blin_18.setObjectName("blin_18")
        self.blin_19 = QtWidgets.QLabel(self.game)
        self.blin_19.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_19.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_19.setText("")
        self.blin_19.setObjectName("blin_19")
        self.blin_20 = QtWidgets.QLabel(self.game)
        self.blin_20.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_20.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_20.setText("")
        self.blin_20.setObjectName("blin_20")
        self.blin_21 = QtWidgets.QLabel(self.game)
        self.blin_21.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_21.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_21.setText("")
        self.blin_21.setObjectName("blin_21")
        self.blin_22 = QtWidgets.QLabel(self.game)
        self.blin_22.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_22.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_22.setText("")
        self.blin_22.setObjectName("blin_22")
        self.blin_23 = QtWidgets.QLabel(self.game)
        self.blin_23.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_23.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_23.setText("")
        self.blin_23.setObjectName("blin_23")
        self.blin_24 = QtWidgets.QLabel(self.game)
        self.blin_24.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_24.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_24.setText("")
        self.blin_24.setObjectName("blin_24")
        self.blin_25 = QtWidgets.QLabel(self.game)
        self.blin_25.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_25.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_25.setText("")
        self.blin_25.setObjectName("blin_25")
        self.blin_26 = QtWidgets.QLabel(self.game)
        self.blin_26.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_26.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_26.setText("")
        self.blin_26.setObjectName("blin_26")
        self.blin_27 = QtWidgets.QLabel(self.game)
        self.blin_27.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_27.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_27.setText("")
        self.blin_27.setObjectName("blin_27")
        self.blin_28 = QtWidgets.QLabel(self.game)
        self.blin_28.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_28.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_28.setText("")
        self.blin_28.setObjectName("blin_28")
        self.blin_29 = QtWidgets.QLabel(self.game)
        self.blin_29.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_29.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_29.setText("")
        self.blin_29.setObjectName("blin_29")
        self.blin_30 = QtWidgets.QLabel(self.game)
        self.blin_30.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_30.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_30.setText("")
        self.blin_30.setObjectName("blin_30")
        self.blin_31 = QtWidgets.QLabel(self.game)
        self.blin_31.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_31.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_31.setText("")
        self.blin_31.setObjectName("blin_31")
        self.blin_32 = QtWidgets.QLabel(self.game)
        self.blin_32.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_32.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_32.setText("")
        self.blin_32.setObjectName("blin_32")
        self.blin_33 = QtWidgets.QLabel(self.game)
        self.blin_33.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_33.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_33.setText("")
        self.blin_33.setObjectName("blin_33")
        self.blin_34 = QtWidgets.QLabel(self.game)
        self.blin_34.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_34.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_34.setText("")
        self.blin_34.setObjectName("blin_34")
        self.blin_35 = QtWidgets.QLabel(self.game)
        self.blin_35.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_35.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_35.setText("")
        self.blin_35.setObjectName("blin_35")
        self.blin_36 = QtWidgets.QLabel(self.game)
        self.blin_36.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_36.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_36.setText("")
        self.blin_36.setObjectName("blin_36")
        self.blin_37 = QtWidgets.QLabel(self.game)
        self.blin_37.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_37.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_37.setText("")
        self.blin_37.setObjectName("blin_37")
        self.blin_38 = QtWidgets.QLabel(self.game)
        self.blin_38.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_38.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_38.setText("")
        self.blin_38.setObjectName("blin_38")
        self.blin_39 = QtWidgets.QLabel(self.game)
        self.blin_39.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_39.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_39.setText("")
        self.blin_39.setObjectName("blin_39")
        self.blin_40 = QtWidgets.QLabel(self.game)
        self.blin_40.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_40.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_40.setText("")
        self.blin_40.setObjectName("blin_40")
        self.blin_41 = QtWidgets.QLabel(self.game)
        self.blin_41.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_41.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_41.setText("")
        self.blin_41.setObjectName("blin_41")
        self.blin_42 = QtWidgets.QLabel(self.game)
        self.blin_42.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_42.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_42.setText("")
        self.blin_42.setObjectName("blin_42")
        self.blin_43 = QtWidgets.QLabel(self.game)
        self.blin_43.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_43.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_43.setText("")
        self.blin_43.setObjectName("blin_43")
        self.blin_44 = QtWidgets.QLabel(self.game)
        self.blin_44.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_44.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_44.setText("")
        self.blin_44.setObjectName("blin_44")
        self.blin_45 = QtWidgets.QLabel(self.game)
        self.blin_45.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_45.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_45.setText("")
        self.blin_45.setObjectName("blin_45")
        self.blin_46 = QtWidgets.QLabel(self.game)
        self.blin_46.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_46.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_46.setText("")
        self.blin_46.setObjectName("blin_46")
        self.blin_47 = QtWidgets.QLabel(self.game)
        self.blin_47.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_47.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_47.setText("")
        self.blin_47.setObjectName("blin_47")
        self.blin_48 = QtWidgets.QLabel(self.game)
        self.blin_48.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_48.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_48.setText("")
        self.blin_48.setObjectName("blin_48")
        self.blin_49 = QtWidgets.QLabel(self.game)
        self.blin_49.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_49.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_49.setText("")
        self.blin_49.setObjectName("blin_49")
        self.blin_50 = QtWidgets.QLabel(self.game)
        self.blin_50.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_50.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_50.setText("")
        self.blin_50.setObjectName("blin_50")
        self.blin_51 = QtWidgets.QLabel(self.game)
        self.blin_51.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_51.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_51.setText("")
        self.blin_51.setObjectName("blin_51")
        self.blin_52 = QtWidgets.QLabel(self.game)
        self.blin_52.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_52.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_52.setText("")
        self.blin_52.setObjectName("blin_52")
        self.blin_53 = QtWidgets.QLabel(self.game)
        self.blin_53.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_53.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_53.setText("")
        self.blin_53.setObjectName("blin_53")
        self.blin_54 = QtWidgets.QLabel(self.game)
        self.blin_54.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_54.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_54.setText("")
        self.blin_54.setObjectName("blin_54")
        self.blin_55 = QtWidgets.QLabel(self.game)
        self.blin_55.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_55.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_55.setText("")
        self.blin_55.setObjectName("blin_55")
        self.blin_56 = QtWidgets.QLabel(self.game)
        self.blin_56.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_56.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_56.setText("")
        self.blin_56.setObjectName("blin_56")
        self.blin_57 = QtWidgets.QLabel(self.game)
        self.blin_57.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_57.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_57.setText("")
        self.blin_57.setObjectName("blin_57")
        self.blin_58 = QtWidgets.QLabel(self.game)
        self.blin_58.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_58.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_58.setText("")
        self.blin_58.setObjectName("blin_58")
        self.blin_59 = QtWidgets.QLabel(self.game)
        self.blin_59.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_59.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_59.setText("")
        self.blin_59.setObjectName("blin_59")
        self.blin_60 = QtWidgets.QLabel(self.game)
        self.blin_60.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_60.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_60.setText("")
        self.blin_60.setObjectName("blin_60")
        self.blin_61 = QtWidgets.QLabel(self.game)
        self.blin_61.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_61.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_61.setText("")
        self.blin_61.setObjectName("blin_61")
        self.blin_62 = QtWidgets.QLabel(self.game)
        self.blin_62.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_62.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_62.setText("")
        self.blin_62.setObjectName("blin_62")
        self.blin_63 = QtWidgets.QLabel(self.game)
        self.blin_63.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_63.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_63.setText("")
        self.blin_63.setObjectName("blin_63")
        self.blin_64 = QtWidgets.QLabel(self.game)
        self.blin_64.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_64.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_64.setText("")
        self.blin_64.setObjectName("blin_64")
        self.blin_65 = QtWidgets.QLabel(self.game)
        self.blin_65.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_65.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_65.setText("")
        self.blin_65.setObjectName("blin_65")
        self.blin_66 = QtWidgets.QLabel(self.game)
        self.blin_66.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_66.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_66.setText("")
        self.blin_66.setObjectName("blin_66")
        self.blin_67 = QtWidgets.QLabel(self.game)
        self.blin_67.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_67.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_67.setText("")
        self.blin_67.setObjectName("blin_67")
        self.blin_68 = QtWidgets.QLabel(self.game)
        self.blin_68.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_68.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_68.setText("")
        self.blin_68.setObjectName("blin_68")
        self.blin_69 = QtWidgets.QLabel(self.game)
        self.blin_69.setGeometry(QtCore.QRect(0, 560, 89, 3))
        self.blin_69.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_69.setText("")
        self.blin_69.setObjectName("blin_69")
        self.blin_70 = QtWidgets.QLabel(self.game)
        self.blin_70.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_70.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_70.setText("")
        self.blin_70.setObjectName("blin_70")
        self.blin_71 = QtWidgets.QLabel(self.game)
        self.blin_71.setGeometry(QtCore.QRect(0, 0, 89, 3))
        self.blin_71.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_71.setText("")
        self.blin_71.setObjectName("blin_71")
        self.blin_72 = QtWidgets.QLabel(self.game)
        self.blin_72.setGeometry(QtCore.QRect(50, 56, 31, 16))
        self.blin_72.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.blin_72.setText("")
        self.blin_72.setObjectName("blin_72")
        self.pushButton_2 = QtWidgets.QPushButton(self.game)
        self.pushButton_2.setGeometry(QtCore.QRect(580, 700, 131, 61))
        self.pushButton_2.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.game)
        self.pushButton_3.setGeometry(QtCore.QRect(810, 790, 93, 51))
        self.pushButton_3.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.game)
        self.pushButton_4.setGeometry(QtCore.QRect(1030, 790, 93, 51))
        self.pushButton_4.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.game)
        self.pushButton_5.setGeometry(QtCore.QRect(1240, 790, 93, 51))
        self.pushButton_5.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.game)
        self.pushButton_6.setGeometry(QtCore.QRect(1450, 790, 93, 51))
        self.pushButton_6.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.game)
        self.pushButton_7.setGeometry(QtCore.QRect(1630, 690, 111, 71))
        self.pushButton_7.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_3 = QtWidgets.QLabel(self.game)
        self.label_3.setGeometry(QtCore.QRect(1580, 880, 191, 20))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.game)
        self.label_4.setGeometry(QtCore.QRect(1050, 20, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.game)
        self.lineEdit_2.setGeometry(QtCore.QRect(800, 700, 113, 61))
        font = QtGui.QFont()
        font.setFamily("Molot")
        font.setPointSize(24)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width:10px;\n"
"\n"
"")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.game)
        self.lineEdit_3.setGeometry(QtCore.QRect(1020, 700, 113, 61))
        font = QtGui.QFont()
        font.setFamily("Molot")
        font.setPointSize(24)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width:10px;\n"
"\n"
"")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.game)
        self.lineEdit_4.setGeometry(QtCore.QRect(1230, 700, 113, 61))
        font = QtGui.QFont()
        font.setFamily("Molot")
        font.setPointSize(24)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width:10px;\n"
"\n"
"")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.game)
        self.lineEdit_5.setGeometry(QtCore.QRect(1440, 700, 113, 61))
        font = QtGui.QFont()
        font.setFamily("Molot")
        font.setPointSize(24)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width:10px;\n"
"\n"
"")
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.inputNumberStudent = QtWidgets.QFrame(self.centralwidget)
        self.inputNumberStudent.setGeometry(QtCore.QRect(110, 340, 1101, 191))
        self.inputNumberStudent.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.inputNumberStudent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inputNumberStudent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputNumberStudent.setObjectName("inputNumberStudent")
        self.label_2 = QtWidgets.QLabel(self.inputNumberStudent)
        self.label_2.setGeometry(QtCore.QRect(110, 70, 191, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.inputNumberStudent)
        self.pushButton.setGeometry(QtCore.QRect(960, 150, 141, 41))
        self.pushButton.setStyleSheet("background-color: rgb(208, 208, 208);")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.inputNumberStudent)
        self.lineEdit.setGeometry(QtCore.QRect(310, 80, 651, 31))
        font = QtGui.QFont()
        font.setFamily("Magnolia Sky")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_hanoi_tower.setText(_translate("MainWindow", "Ханойские башни"))
        self.pushButton_2.setText(_translate("MainWindow", "СТАРТ"))
        self.pushButton_3.setText(_translate("MainWindow", "P1"))
        self.pushButton_4.setText(_translate("MainWindow", "P2"))
        self.pushButton_5.setText(_translate("MainWindow", "P3"))
        self.pushButton_6.setText(_translate("MainWindow", "P4"))
        self.pushButton_7.setText(_translate("MainWindow", "Конец"))
        self.label_3.setText(_translate("MainWindow", "Кол-во итераций: 0"))
        self.label_4.setText(_translate("MainWindow", "Минимальное кол-во итераций : 0"))
        self.lineEdit_2.setText(_translate("MainWindow", "777"))
        self.lineEdit_3.setText(_translate("MainWindow", "777"))
        self.lineEdit_4.setText(_translate("MainWindow", "777"))
        self.lineEdit_5.setText(_translate("MainWindow", "777"))
        self.label_2.setText(_translate("MainWindow", "Введите ID студента:"))
        self.pushButton.setText(_translate("MainWindow", "СТАРТ!"))
        self.lineEdit.setInputMask(_translate("MainWindow", "99999999"))
        self.lineEdit.setText(_translate("MainWindow", "12345678"))


"""Подключение библиотек для работы с PyQt5"""
from PyQt5 import QtWidgets, QtCore, Qt, QtGui
from PyQt5.QtWidgets import QWidget
from PyQt5.QtCore import QPropertyAnimation, QRect, QTimer, QCoreApplication
import sys,time, psycopg2 
import pprint
from copy import deepcopy

"""Создание главного класса"""
class Main_Window(QtWidgets.QMainWindow):
    """Инициирование локальных(переменных, которые будут работать только в этом классе)"""
    def __init__(self):
        super(Main_Window,self).__init__() # наследование из класса
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self) 
        
        """Создание простых перменных-маркеров"""
        self.nums = 0
        self.poz1 = 0
        
        """Создание делений id студента"""
        self.number1 = 0
        self.number2 = 0
        self.number3 = 0
        self.number4 = 0

        """Создание действий на кнопки"""              
        self.ui.pushButton.clicked.connect(self.CheckNumberAndDrob)
        self.ui.pushButton_3.clicked.connect(self.count_hod)
        self.ui.pushButton_4.clicked.connect(self.count_hod)
        self.ui.pushButton_5.clicked.connect(self.count_hod)
        self.ui.pushButton_6.clicked.connect(self.count_hod)

        self.ui.pushButton_2.clicked.connect(self.count_hod)
        self.ui.pushButton_7.clicked.connect(self.count_hod)     

        """Сокрытие гравного фрейма"""
        self.ui.game.hide()     

    def CheckNumberAndDrob(self):
        """
        Проверка данных, создание делений и отображение пирамидки
        """
        self.shirina = 21
        number = int(self.ui.lineEdit.text())
        b = map(int, str(number))
        self.number1 = number//1000000
        self.number2 = (number//10000)%100
        self.number3 = (number//100)%100
        self.number4 = (number%100)
        self.piromids = {}
        count = 80
        b = list(b)
        for i in range(1,9):
            num = []       
            for j in range(b[i-1]):
                num.append(j+1+count)
            self.piromids[i] = num
            count = count-10
     
        self.count_hod()
      
        self.ui.inputNumberStudent.hide()
        self.draw_blin()
        self.ui.game.show() 
        
    def count_hod(self):
        if self.sender().objectName() == "pushButton_2":
            self.ui.label_3.setText(f"Кол-во итераций: {0}")
            self.nums = 0
            self.draw_blin()

        elif self.sender().objectName() == "pushButton_3":
            number_pers = int(self.ui.lineEdit_2.text())
            persent = (self.count*number_pers)//100
            ost = (self.count*number_pers)%100
            self.answer = self.find_pers(persent,ost)
            self.ui.label_3.setText(f"Кол-во итераций: {persent}.{ost}")
            self.nums = 1
            self.draw_blin()
        
        elif self.sender().objectName() == "pushButton_4":
            number_pers = int(self.ui.lineEdit_3.text())
            persent = (self.count*number_pers)//100
            ost = (self.count*number_pers)%100
            self.answer = self.find_pers(persent,ost)
            self.ui.label_3.setText(f"Кол-во итераций: {persent}.{ost}")
            self.nums = 1
            self.draw_blin()
        
        elif self.sender().objectName() == "pushButton_5":
            number_pers = int(self.ui.lineEdit_4.text())
            persent = (self.count*number_pers)//100
            ost = (self.count*number_pers)%100
            self.answer = self.find_pers(persent,ost)
            self.ui.label_3.setText(f"Кол-во итераций: {persent}.{ost}")
            self.nums = 1
            self.draw_blin()

        elif self.sender().objectName() == "pushButton_6":
            number_pers = int(self.ui.lineEdit_5.text())
            persent = (self.count*number_pers)//100
            ost = (self.count*number_pers)%100
            self.answer = self.find_pers(persent,ost)
            self.ui.label_3.setText(f"Кол-во итераций: {persent}.{ost}")
            self.nums = 1
            self.draw_blin()

        elif self.sender().objectName() == "pushButton_7":
            number_pers = int(self.ui.lineEdit_2.text())
            persent = self.count
            ost = (self.count//100)%100
            self.answer = self.find_pers(persent,ost)
            self.ui.label_3.setText(f"Кол-во итераций: {persent}.{ost}")
            self.nums = 1
            self.draw_blin()

        else:
            self.count = 0
            self.dubl_pir = deepcopy(self.piromids)
            for i in self.piromids:
                if i == 1:
                    for j in range(len(self.dubl_pir[i])):
                        self.dubl_pir[3].append(self.dubl_pir[i][j])

                    self.count+=len(self.dubl_pir[1])
                elif i == 2:
                    for j in range(len(self.dubl_pir[i])):
                        self.dubl_pir[i+1].append(self.dubl_pir[i][j])
                    self.count+=len(self.dubl_pir[i])
                elif i == 8:
                    continue  
                else:
                    for j in range(len(self.dubl_pir[i])):
                        self.dubl_pir[i+1].append(self.dubl_pir[i][j])
                    self.count+=len(self.dubl_pir[i])      
            self.ui.label_4.setText(f"Минимальное кол-во итераций: {self.count}")
            self.ui.lineEdit_2.setText(str(self.number1))
            self.ui.lineEdit_3.setText(str(self.number2))
            self.ui.lineEdit_4.setText(str(self.number3))
            self.ui.lineEdit_5.setText(str(self.number4))


    def find_pers(self,persent,ost):
        count = 0
        counts = 60
        dubl_pir = deepcopy(self.piromids)
        self.poz1 = 0
        if ost == 0:
             self.poz1 = 0
        if 0<ost<=25:
            self.poz1 = 1
        elif 25<ost<=75:
            self.poz1 = 2
        elif 75<ost<99:
            self.poz1 = 3
 
        for i in self.piromids:
                number = []
                if count == persent:
                    return dubl_pir
                if i == 1:
                    for j in range(len(dubl_pir[i])):
                        dubl_pir[3].append(dubl_pir[i][j])
                        number.append(dubl_pir[i][j])                       
                        if count == persent:
                            num = i
                            for s in number:
                                dubl_pir[num].remove(s)
                            for s in range(len(dubl_pir[3])-1,0,-1):
                                dubl_pir[3][s] = s+1+ counts
                            for s in range(len(dubl_pir[i])-1,0,-1):
                                dubl_pir[1][s] = s+1+ counts
                            return dubl_pir
                        else:
                            count+=1
                    dubl_pir[i].clear()
                    for s in range(len(dubl_pir[3])-1,0,-1):
                        dubl_pir[3][s] = s+1+ counts

                elif i == 2:
                    for j in range(len(dubl_pir[i])):
                        dubl_pir[i+1].append(dubl_pir[i][j])
                        number.append(dubl_pir[i][j])                       
                        if count == persent:
                            num = i
                            for s in number:
                                dubl_pir[num].remove(s)
                            for s in range(len(dubl_pir[3])-1,0,-1):
                                dubl_pir[3][s] = s+1+ counts
                            for s in range(len(dubl_pir[i])-1,0,-1):
                                dubl_pir[2][s] = s+1+ counts
                            return dubl_pir
                        else:
                            count+=1
                    dubl_pir[i].clear()
                    for s in range(len(dubl_pir[3])-1,-1,-1):
                        dubl_pir[3][s] = s+1+ counts
                    counts = counts - 10
                elif i == 8:
                    if count == persent:
                            return dubl_pir
                    else:
                            count+=1
                else:
                    for j in range(len(dubl_pir[i])):
                        dubl_pir[i+1].append(dubl_pir[i][j])
                        number.append(dubl_pir[i][j])                                             
                        if count == persent:
                            num = i
                            for s in number:
                                dubl_pir[num].remove(s)
                            for s in range(len(dubl_pir[i+1])-1,-1,-1):
                                dubl_pir[i+1][s] = s+1+ counts
                            for s in range(len(dubl_pir[i])-1,-1,-1):
                                dubl_pir[i][s] = s+1+ counts+10
                            return dubl_pir
                        else:
                            count+=1
                    dubl_pir[i].clear()
                    for s in range(len(dubl_pir[i+1])-1,0,-1):
                        dubl_pir[i+1][s] = s+1+ counts
                    counts = counts - 10 


    def draw_blin(self):
        if self.nums == 0:
            spisok = [self.ui.shpil8,self.ui.shpil7,self.ui.shpil6,self.ui.shpil5,self.ui.shpil4,self.ui.shpil3,self.ui.shpil2,self.ui.shpil1]
            blins = [self.ui.blin,self.ui.blin_2,self.ui.blin_3,self.ui.blin_4,self.ui.blin_5,self.ui.blin_6,self.ui.blin_7,self.ui.blin_8,self.ui.blin_9,
                     self.ui.blin_10,self.ui.blin_11,self.ui.blin_12,self.ui.blin_13,self.ui.blin_14,self.ui.blin_15,self.ui.blin_16,self.ui.blin_17,self.ui.blin_18,
                     self.ui.blin_19,self.ui.blin_20,self.ui.blin_21,self.ui.blin_22,self.ui.blin_23,self.ui.blin_24,self.ui.blin_25,self.ui.blin_26,self.ui.blin_27,
                     self.ui.blin_28,self.ui.blin_29,self.ui.blin_30,self.ui.blin_31,self.ui.blin_32,self.ui.blin_33,self.ui.blin_34,self.ui.blin_35,self.ui.blin_36,
                     self.ui.blin_37,self.ui.blin_38,self.ui.blin_39,self.ui.blin_40,self.ui.blin_41,self.ui.blin_42,self.ui.blin_43,self.ui.blin_44,self.ui.blin_45,
                     self.ui.blin_46,self.ui.blin_47,self.ui.blin_48,self.ui.blin_49,self.ui.blin_50,self.ui.blin_51,self.ui.blin_52,self.ui.blin_53,self.ui.blin_54,
                     self.ui.blin_55,self.ui.blin_56,self.ui.blin_57,self.ui.blin_58,self.ui.blin_59,self.ui.blin_60,self.ui.blin_61,self.ui.blin_62,self.ui.blin_63,
                     self.ui.blin_64,self.ui.blin_65,self.ui.blin_66,self.ui.blin_67,self.ui.blin_68,self.ui.blin_69,self.ui.blin_70,self.ui.blin_71,self.ui.blin_72]
            count = 0
            for i in range(len(spisok)):
                x = spisok[i].x()
                y = spisok[i].y()
                y = y+497
                for s in range(len(self.piromids[i+1])-1,-1,-1):
                            blins[count].setGeometry(x-(self.piromids[i+1][s]//2), y, self.piromids[i+1][s] , 7)
                            blins[count].setText(str(self.piromids[i+1][s]))
                            count+=1
                            y= y-8
                

        elif self.nums == 1:
            spisok = [self.ui.shpil8,self.ui.shpil7,self.ui.shpil6,self.ui.shpil5,self.ui.shpil4,self.ui.shpil3,self.ui.shpil2,self.ui.shpil1]
            blins = [self.ui.blin,self.ui.blin_2,self.ui.blin_3,self.ui.blin_4,self.ui.blin_5,self.ui.blin_6,self.ui.blin_7,self.ui.blin_8,self.ui.blin_9,
                     self.ui.blin_10,self.ui.blin_11,self.ui.blin_12,self.ui.blin_13,self.ui.blin_14,self.ui.blin_15,self.ui.blin_16,self.ui.blin_17,self.ui.blin_18,
                     self.ui.blin_19,self.ui.blin_20,self.ui.blin_21,self.ui.blin_22,self.ui.blin_23,self.ui.blin_24,self.ui.blin_25,self.ui.blin_26,self.ui.blin_27,
                     self.ui.blin_28,self.ui.blin_29,self.ui.blin_30,self.ui.blin_31,self.ui.blin_32,self.ui.blin_33,self.ui.blin_34,self.ui.blin_35,self.ui.blin_36,
                     self.ui.blin_37,self.ui.blin_38,self.ui.blin_39,self.ui.blin_40,self.ui.blin_41,self.ui.blin_42,self.ui.blin_43,self.ui.blin_44,self.ui.blin_45,
                     self.ui.blin_46,self.ui.blin_47,self.ui.blin_48,self.ui.blin_49,self.ui.blin_50,self.ui.blin_51,self.ui.blin_52,self.ui.blin_53,self.ui.blin_54,
                     self.ui.blin_55,self.ui.blin_56,self.ui.blin_57,self.ui.blin_58,self.ui.blin_59,self.ui.blin_60,self.ui.blin_61,self.ui.blin_62,self.ui.blin_63,
                     self.ui.blin_64,self.ui.blin_65,self.ui.blin_66,self.ui.blin_67,self.ui.blin_68,self.ui.blin_69,self.ui.blin_70,self.ui.blin_71,self.ui.blin_72]
            count = 0
            spik = 0
            for i in range(len(spisok)):
                x = spisok[i].x()
                y = spisok[i].y()
                y = y+491

                for s in range(len(self.answer[i+1])-1,-1,-1):
                            blins[count].setGeometry(x-(self.answer[i+1][s]//2), y, self.answer[i+1][s] , 10)
                            blins[count].setText(str(self.answer[i+1][s]))
                            count+=1
                            y= y-11
                spik = i

            if self.poz1 == 0:
                blins[count-1].hide()

            if self.poz1 == 1:
                    first = 0
                    for i in range(1,len(self.answer)):
                         if len(self.answer[i]) != 0 and first == 0:
                                       first = 1
                                       spik = spisok[i-1]
                                       x = spik.x()
                                       y = spik.y()
                                       last = self.answer[i][-1]
                                       blins[count-1].setGeometry(x + 30, y + 150, last , 10)
                                       blins[count-1].setText(str(last))
                                       blins[count-1].show()
                                      

            elif self.poz1 == 2:
                    first = 0
                    for i in range(1,len(self.answer)):
                         if len(self.answer[i]) != 0 and first == 0:
                                       first = 1
                                       spik = spisok[i-1]
                                       x = spik.x()
                                       y = spik.y()
                                       last = self.answer[i][-1]
                                       blins[count-1].setGeometry(x + 50, y + 290, last , 10)
                                       blins[count-1].setText(str(last))
                                       blins[count-1].show()
                                       

            elif self.poz1 == 3:
                    first = 0
                    for i in range(1,len(self.answer)):
                         if len(self.answer[i]) != 0 and first == 0:
                                       first = 1
                                       spik = spisok[i-1]
                                       x = spik.x()
                                       y = spik.y()
                                       last = self.answer[i][-1]
                                       blins[count-1].setGeometry(x + 80, y + 150, last , 10)
                                       blins[count-1].setText(str(last))
                                       blins[count-1].show()
                                       
                    
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    application = Main_Window()
    application.show()
    sys.exit(app.exec_()) 
